<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>MakerBot RPC API</Title>
    <Company />
    <Description>Provides API access management for the Croissant API using JSON-RPC.</Description>
    <PackageTags>MakerBot;JSON-RPC;API</PackageTags>
    <PackageReadmeFile>PROTOCOL.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Makaretu.Dns.Multicast" Version="0.27.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.32" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>MakerBot.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <None Include="PROTOCOL.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
