<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mtconnect.AdapterSdk.Source" Version="2.6.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MakerBot.Rpc\MakerBot.Rpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="adapterconfig.example.json" Pack="true" PackagePath="contentFiles\any\any" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>MakerBot.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
