<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MakerBot.Terminal</AssemblyName>
    <RootNamespace>MakerBot.Terminal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Consoul" Version="2.0.2" />
    <PackageReference Include="Mtconnect.ShdrAdapter" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mtconnect.MakerBotAdapter\Mtconnect.MakerBotAdapter.csproj" />
  </ItemGroup>

</Project>
